### ISSUE TITLE
Current pip download missing HTML templates and JS?

### ISSUE THREAD

**Issue by pjmcdermott** [pinax/pinax-blog#103]
I just did a fresh install of pinax-blog into my existing Django project. `pip freeze` reports `pinax-blog==6.3.1`, so it seems like pip is accessing the guthub master.

I get this error message on visiting the blog page:

```
django.template.exceptions.TemplateDoesNotExist
django.template.exceptions.TemplateDoesNotExist: pinax/blog/blog_list.html, blog/post_list.html
```
Checking my installation, I can indeed that *.html is missing from `pinax/blog/templates/pinx/blog`. But *.xml files are there. After further poking around I can see that I am also missing `pinax/blog/static/js/admin_post_form.js`.

Something wrong with the current `setup.py` or the deployment to `PyPi`?

**Comment by pjmcdermott** [comment]
Just found out that `blog_list.html` and `post_list.html` mentioned in the error message do not exist in the current github archive. Just tried switching to official release 6.1.1 but the same issues exist...

**Comment by paltman** [comment]
They are in `pinax-templates`.

```
pip install pinax-templates
```

Then in `settings.py`:

```python
INSTALLED_APPS += ["pinax.templates"]
```

**Comment by pjmcdermott** [comment]
OK. Doesn't that mean that `pinax-templates` should be included in `setup.py`, and the need to add to `INSTALLED_APPS` mentioned in the installation notes. Therefore still an unresolved bug?

**Comment by paltman** [comment]
No because you might want to use your own templates.
