### ISSUE TITLE
Image inline Admin for new post not registering

### ISSUE THREAD

**Issue by doktormerlin** [pinax/pinax-blog#121]
I recently added pinax-blog (and pinax-images) to my project, but there is no InlineAdmin for the images to be added to the posts as stated in the documentation.

Because of that there is no way to add pictures to a post, adding them manually in the post set does not give you the numbers you need to reference.

Steps to reproduce:

1. Start a new django project
2. Add pinax-blog and pinax-images to the installed_apps
3. That's it, no form to upload images while creating a post

**Comment by KatherineMichel** [comment]
@doktormerlin Hello, are you still working through this issue or resolved? Maybe I'm misunderstanding your question, but I'm able to create a new blog post in admin, create a blog post image set, then go back into the blog post markdown and add the image markdown for an image from the post image set. When I view the site, it works. Are you trying to do something different than this?

**Comment by KatherineMichel** [comment]
I see, it looks like there is a PR for this. https://github.com/pinax/pinax-blog/pull/123

**Comment by KatherineMichel** [comment]
Closed by #123
