### ISSUE TITLE
django 3.0.4 - cannot import name 'python_2_unicode_compatible' 

### ISSUE THREAD

**Issue by dannyblaker** [pinax/pinax-blog#128]
import error installing with django 3.0.4:
`cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding`

Issue:
Django 3 has [removed](https://docs.djangoproject.com/en/3.0/releases/3.0/) the `django.utils.encoding.python_2_unicode_compatible()` api. 

Solution:
in `blog\models.py` and `images\models.py`:

replace: `from django.utils.encoding import python_2_unicode_compatible`
with: `from six import python_2_unicode_compatible`

🌻

**Comment by KatherineMichel** [comment]
Thank you for your issue. @mfonism might be working on fixing that. Not sure. If not, I'm happy to receive a PR from you to fix, if you are interested.

**Comment by mfonism** [comment]
Hi @dannyblaker,

I've made plans to work on this issue (and other related issues) this weekend.

But if you have a PR for it, or are already working on one, (or are even planning to work on one 🙈), please let @KatherineMichel know, so we can channel our efforts into fixing other issues.

Thank you for your issue.

**Comment by KatherineMichel** [comment]
@dannyblaker... a new release has been tagged and published. Thank you! https://pypi.org/project/pinax-blog/

**Comment by dannyblaker** [comment]
> @dannyblaker... a new release has been tagged and published. Thank you! https://pypi.org/project/pinax-blog/

Awesome! Thanks @KatherineMichel @mfonism & everyone :)

**Comment by IamOmaR22** [comment]
**Use**  -  from six import python_2_unicode_compatible

Instead of  -  from django.utils.encoding import python_2_unicode_compatible

I hope it will solve the problem.
