### ISSUE TITLE
Django 3.x - cannot import name 'curry' from 'django.utils.functional'

### ISSUE THREAD

**Issue by mohsenone** [pinax/pinax-blog#130]
**Describe the bug**
ImportError: cannot import name 'curry' from 'django.utils.functional' 

**Reproduce behavior**
* Create new virtualenv
* pip install `django`, `pinax-blog`
* Create new project with `django-admin`
* Add `pinax.blog` and `pinax.images` to `INSTALLED_APPS`
* Add pinax.blog.urls to urlpatterns
* replace: `from django.utils.encoding import python_2_unicode_compatible`
  with: `from six import python_2_unicode_compatible` due to [this issue](https://github.com/pinax/pinax-blog/issues/128)
* run `python3 manage.py runserver` or `python3 manage.py migrate`

**Comment by KatherineMichel** [comment]
It looks like this needs to be updated as part of dropping Python 2.x support. @mfonism has a branch in the works to do that, but I don't think `curry` has been updated yet. https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis
https://github.com/mfonism/pinax-blog/tree/2020.03.14/update-python-and-django-support

**Comment by tiholic** [comment]
@KatherineMichel 
https://code.djangoproject.com/ticket/10479

You may simply change the imports from `django.utils.functional import curry` to `from funtools import partial as curry`

**Comment by KatherineMichel** [comment]
@mohsenone, @tiholic... a new release has been tagged and published. Thank you! https://pypi.org/project/pinax-blog/

**Comment by neilmillard** [comment]
Managed to recreate this bug from a fresh 8.0.0 install.
```
File "/data/neil/.cache/pypoetry/virtualenvs/sc-blog-a7R5rCuA-py3.8/lib/python3.8/site-packages/pinax/blog/admin.py", line 3, in <module>
    from django.utils.functional import curry
ImportError: cannot import name 'curry' from 'django.utils.functional'
```

**Comment by mfonism** [comment]
Oops! I inadvertently missed this one 🙈!!

Just bit me in a side project a few minutes ago... But I see you have a PR for this, @neilmillard.

**Comment by KatherineMichel** [comment]
@mohsenone @neilmillard @tiholic @mfonism I am so sorry, everyone. I could have sworn I fixed this! Otherwise, would not have closed issue. Maybe I pushed to the wrong branch. I've merged @neilmillard's PR and published a new package. https://pypi.org/project/pinax-blog/8.0.1/

**Comment by nickmccullum** [comment]
> @KatherineMichel https://code.djangoproject.com/ticket/10479
> 
> You may simply change the imports from `django.utils.functional import curry` to `from funtools import partial as curry`

In case anyone comes across this, the import is typod here and should be `functools` not `funtool`.
