### ISSUE TITLE
Add states of a post instead of binary published or not

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-blog#23]
This helps with #34 as well.

**Comment by paltman** [comment]
I think this can be a list of states that is pulled from a setting but ships with a default of:

    [
        "Published",
        "Draft"
    ]

Furthermore, I think we should always have these two statuses and then the setting can allow one to insert statuses that live along the continuum between `Draft` and `Published`.

**Comment by jtauber** [comment]
What is nice about having a flexible states set is people can layer workflow on top if they need to.

In other words, pinax.blog can stay agnostic as to *how* posts change state (or can provide a very simple default workflow) but if there are other workflows that involve signoff, etc, they are supported.
