### ISSUE TITLE
Do we really need a Revision model?

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-blog#37]
@jtauber do we ever use this in all the instances we use this software?

Does anyone else?

**Comment by jtauber** [comment]
I can't say I've explicitly used it but I also like the idea that we have the full edit history of posts.

**Comment by rizumu** [comment]
Now that there is https://github.com/etianen/django-reversion it doesn't seem necessary to build it into the project.

**Comment by jtauber** [comment]
Yeah, I'm all for just using something like that. The thing we considered important when we first implemented the feature on the eldarion.com blog was knowing what the blog said at a particular time (i.e. having an audit trail after initial publication more than simply capturing versions during drafting)

**Comment by ossanna16** [comment]
Any further discussion on this? 😊

**Comment by swilcox** [comment]
I'm definitely of the "less is more" camp. Keep things smaller and simpler is good.

**Comment by jtauber** [comment]
I still think it's important for (particularly a corporate) blog to know what content was visible at a point in time, which was the point of the Revision model. I'm +0 on using django-reversion for it instead and -0 on losing the functionality all together.

**Comment by paltman** [comment]
I actually think this is important to keep now if we are considering auto-saves on #62
