### ISSUE TITLE
Document the use of custom editors in the admin at the project level

### ISSUE THREAD

**Issue by ShaunGuarini** [pinax/pinax-blog#42]
I find it much easier to use CK Editor when building a blog. Would be great if you added that.

I'm also running into a lot of errors when using this so going to give it some time and come back!

**Comment by jtauber** [comment]
It would be nice if the choice of editor was kept decoupled from the app itself and just provided either by another app or in a starter project.

**Comment by paltman** [comment]
Yeah, I think the choice of editor would best be setup as part of the project at the site level. I have done this with my personal blog, paltman.com, using the ACE Editor. I'll see if I can't turn what I did into some documentation for this app.

Also, please do report issues here as you find them!  Thanks!

**Comment by paltman** [comment]
Hope you didn't mind, but modified the title of the issue to reflect what I think we should do
