### ISSUE TITLE
settings.AUTH_USER_MODEL

### ISSUE THREAD

**Issue by cdvv7788** [pinax/pinax-blog#45]
I am getting an error regarding the user model used:
blog.Post.author: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
blog.Revision.author: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

This setting defaults to django's default user model, but is preferred to support custom users: https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#substituting-a-custom-user-model

**Comment by cdvv7788** [comment]
Added a pull request to handle this: https://github.com/pinax/pinax-blog/pull/46

**Comment by ckald** [comment]
Any update on this?

**Comment by tmmgarcia** [comment]
Same issue here.
