### ISSUE TITLE
Assume HTML in summary

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-blog#63]
to fix #60 we changed content to be html but I've just found a case where I had to make the summary html too. Similar change but to summary element

**Comment by ossanna16** [comment]
Would this be a good "first-timers-only" or "difficulty: easy" issue? It sounds like it could be 😊

**Comment by gautamramk** [comment]
I am a first timer, could I try for it?

**Comment by jtauber** [comment]
@gautamramk there is already a pull-request, perhaps you can review and test it?

**Comment by paltman** [comment]
Go for it!

**Comment by gautamramk** [comment]
Could someone give me an idea how to review the already existing pull request? I am very new to this.

**Comment by paltman** [comment]
@gautamramk glad to have you!

Typically you'd want to clone the original repo of the fork that is submitting the request and check out the branch in question.

```
git clone git@github.com:FlaviaBastos/pinax-blog.git
cd pinax-blog
git checkout html-summary
```

Then you'd want to test that the changes actually work. :) Being that this is an Atom feed the previous instructions to clone the code locally are probably not ideal but I'll leave them in case it's useful for you to know how to get the fork's code local for easier inspection.

Let's start a blog starter project but swap out the PyPI released version of `pinax-blog` for Flavia's branch.

```
pip install pinax-cli
pinax start --dev blog testblog
cd testblog
```

Now, edit `requirements.txt` and replace the `pinax-blog==` line with:

```
-e git+https://github.com/FlaviaBastos/pinax-blog@html-summary#egg=pinax-blog
```

Now run:

```
pip install -r requirements.txt
./manage.py migrate
./magage.py loaddata sites
./manage.py createsuperuser   # provide the input and create yourself an account
./manage.py runserver
```

Browse to http://localhost:8000/admin/, log in and create some posts.

Now go to:  http://localhost:8000/feed/all/atom/ and copy and paste the contents into:

https://validator.w3.org/feed/#validate_by_input

Check to see if it validates but also visually inspect the `<summary` node to see if contains the expected output.

**Comment by gautamramk** [comment]
Thanks a lot for guidance, I shall do it.
