### ISSUE TITLE
Allow setting of publication date other than now

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-blog#74]
At the moment if I want the publication date (e.g. what's shown in the dateline and, in many cases, the URL) to be other than when I actually switched it from "draft" to "published", I have to use the shell.

It would be nice if there was a way to publish with a datetime other than now.

**Comment by ossanna16** [comment]
Would this be a good "first-timers-only" or "difficulty: easy" issue? I added new labels so we can track the difficulty of issues better 😊

**Comment by paltman** [comment]
@ossanna16 yes, this is a pretty straightforward modification of the admin.  What is our standard for writing up a good issue for `first-timers-only`?

**Comment by ossanna16** [comment]
@paltman This https://github.com/pinax/pinax/issues/102 is an example of a `first-timers-only` issue. I'd be happy to help you write this one. Please just ping me and let me know how I can help :)

**Comment by paltman** [comment]
Fixed in `v5.0.0`
