### ISSUE TITLE
What is the best way to enable per-user blogs?

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-blog#77]

**Comment by jtauber** [comment]
so one way to do it would just be you filter by author and don't even try to model them as separate blogs

**Comment by jtauber** [comment]
although note one use-case we talked about in an LMS context was a blog per student per course

**Comment by paltman** [comment]
Yeah, I think we need to at least have a top level `Blog` object.

**Comment by paltman** [comment]
See #93

**Comment by KatherineMichel** [comment]
Closing this issue. Seems to have been implemented through #93 and documented in README.
