### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by gopar** [pinax/pinax-blog#80]
I keep getting a 
`RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.` whenever I tried to run the app.

I followed the exact instructions on the docs, installed deps and did **not** install `creole` since I'm using py3.

Any ideas?

Django 1.9.2
Py 3.4.3

**Comment by ossanna16** [comment]
@gopar Would you mind joining our Pinax Slack team (http://slack.pinaxproject.com) and asking your question there? We're usually able to help you faster in Slack. Thank you! :)

**Comment by paltman** [comment]
I think you are missing the sites framework in your settings.py.  pinax-blog needs the sites framework.

**Comment by paltman** [comment]
The resolution is to install the sites framework.
