### ISSUE TITLE
NoReverseMatch at /admin/blog/post/

### ISSUE THREAD

**Issue by garcianavalon** [pinax/pinax-blog#84]
Hi,

I have installed the last version of Pinax and I'm getting an error in the admin page. If I try to access /admin/blog/post/ I get a` NoReverseMatch u'pinax_blog' is not a registered namespace`. I only get this error in the /post/ sections, the rest are working fine.

I have the following code:
At settings.py
```
INSTALLED_APPS = (
    ...
    'pinax.blog',
...
)
```

at urls.py
`url(r"^blog/", include("pinax.blog.urls")),
`
I have also done a `python manage.py migrate`.

Any idea of whats going on? The rest of the sections work perfectly.
Cheers

![captura de pantalla 2016-07-10 a las 18 00 07](https://cloud.githubusercontent.com/assets/1436781/16714591/82c4e9a0-46c8-11e6-91ae-748e4e45001f.png)
![captura de pantalla 2016-07-10 a las 18 00 27](https://cloud.githubusercontent.com/assets/1436781/16714592/82c667f8-46c8-11e6-8fe4-112a769ba95a.png)

**Comment by paltman** [comment]
You need to add the `pinax_blog` namespace to the urls definition:

Like so:
https://github.com/pinax/pinax-starter-projects/blob/blog/project_name/urls.py#L9

**Comment by garcianavalon** [comment]
Thanks @paltman!
The documentation is outdated, as the namespace part is missing in the installation instructions. I can make you a pull request with the fix

**Comment by jtauber** [comment]
@garcianavalon that'd be great, thanks!
