### ISSUE TITLE
Add biblion to pinax-blog migration

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-blog#85]
either in docs or somehow as something runnable via management command:

https://gist.github.com/paltman/73cf67290df3e92790c29934fa8a56e5

**Comment by KatherineMichel** [comment]
Is this still a thing that needs to happen? @paltman

**Comment by KatherineMichel** [comment]
Closing issue. Does not seem relevant at this point. Feel free to re-open if I'm wrong.
