### ISSUE TITLE
RuntimeErorr on the very first migration

### ISSUE THREAD

**Issue by vleong2332** [pinax/pinax-blog#88]
When running the first migration after installing, this error was thrown:

```
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in a
n application in INSTALLED_APPS.
```

I had to add `django.contrib.sites` to the `INSTALLED_APPS` and set `SITE_ID = 1` in `settings.py`.

Is this related to #69?

**Comment by pd-Shah** [comment]
I have the same issue

**Comment by KatherineMichel** [comment]
@pd-Shah Were you able to fix it using the guidance that was added to the README in this PR? https://github.com/pinax/pinax-blog/pull/89/files
