### ISSUE TITLE
Got error when install - blog.Post.image_set: (fields.E300) Field defines a relation with model 'ImageSet'

### ISSUE THREAD

**Issue by wyx2000** [pinax/pinax-blog#98]
ERRORS:
blog.Post.image_set: (fields.E300) Field defines a relation with model 'ImageSet', which is either not installed, or is abstract.

Any idea?
thanks

**Comment by grahamu** [comment]
@wyx2000  I believe pinax-blog v6.0.2 release fixes this issue with documentation indicating the need to add pinax-images to SETTINGS. Please close this issue if so, thanks!

https://github.com/pinax/pinax-blog/releases/tag/v6.0.2
